<template>
  <div class="resource-page">
    <ResourceHeader title="插件管理" description="管理当前应用的插件版本、发布状态与启用状态。" action-text="添加托管插件" @action="openManaged" />
    <div class="toolbar"><ElInput v-model="search" placeholder="搜索插件名称或标识" clearable class="search" @keyup.enter="loadPlugins"><template #prefix><ArtSvgIcon icon="ri:search-line" /></template></ElInput><div class="filters"><ElSelect v-model="category" placeholder="全部分类" @change="loadPlugins"><ElOption label="全部分类" value="all" /><ElOption label="支付插件" value="payment" /><ElOption label="实名认证" value="realname" /><ElOption label="其他插件" value="other" /></ElSelect><ElButton :loading="loading" plain @click="loadPlugins"><ArtSvgIcon icon="ri:refresh-line" />刷新目录</ElButton></div></div>
    <div class="source-filter" v-if="sources.length"><span>插件源：</span><ElTag v-for="source in sources" :key="source.id" :type="source.state === 'ok' ? 'success' : source.state === 'error' ? 'danger' : 'info'" effect="plain">{{ source.name || source.url }}</ElTag></div>
    <ElCard shadow="never" class="table-card" v-loading="loading"><div v-if="!filteredRows.length && !loading" class="empty"><ArtSvgIcon icon="ri:apps-2-line" /><strong>暂无插件</strong><span>请先添加插件源，或调整搜索条件。</span><ElButton type="primary" @click="goSources">管理插件源</ElButton></div><ElTable v-else :data="filteredRows" stripe><ElTableColumn label="插件" min-width="280"><template #default="{ row }"><div class="name"><span :class="['icon', colorFor(row.category)]"><ArtSvgIcon :icon="row.icon || 'ri:puzzle-line'" /></span><div><b>{{ row.name }}</b><small>{{ row.id }} · {{ row.source || (row.local ? '内置插件' : '远程源') }}</small></div></div></template></ElTableColumn><ElTableColumn prop="category" label="分类" width="130"><template #default="{row}">{{ categoryText(row.category) }}</template></ElTableColumn><ElTableColumn label="来源" width="120"><template #default="{row}"><ElTag :type="row.local ? 'info' : 'warning'" effect="light">{{ row.local ? '内置' : '远程' }}</ElTag></template></ElTableColumn><ElTableColumn prop="version" label="版本" width="110" /><ElTableColumn label="状态" width="110"><template #default="{row}"><span class="status"><i :class="row.enabled ? 'on' : ''"></i>{{ row.enabled ? '已启用' : '未启用' }}</span></template></ElTableColumn><ElTableColumn label="操作" width="180" fixed="right"><template #default="{row}"><ElButton v-if="row.remote && !row.local" link type="primary" :loading="downloadingId === row.id" @click="download(row)">{{ row.downloadUrl ? '下载' : '无下载包' }}</ElButton><ElButton link :type="row.enabled ? 'warning' : 'success'" :loading="togglingId === row.id" @click="toggle(row)">{{ row.enabled ? '停用' : '启用' }}</ElButton></template></ElTableColumn></ElTable></ElCard><div class="notice"><ArtSvgIcon icon="ri:information-line" />同一分类的插件启用时会自动停用该分类其他插件；付费价格和权益将在插件商业化模块中配置。</div>
    <ElDialog v-model="managedDialog" title="添加托管插件" width="520px"><ElForm :model="managedForm" label-position="top"><ElFormItem label="插件标识"><ElInput v-model="managedForm.pluginId" placeholder="例如 payment-pro" /></ElFormItem><ElFormItem label="插件名称"><ElInput v-model="managedForm.name" /></ElFormItem><ElFormItem label="分类"><ElSelect v-model="managedForm.category" class="full-width"><ElOption label="支付插件" value="payment" /><ElOption label="实名认证" value="realname" /><ElOption label="其他插件" value="other" /></ElSelect></ElFormItem><ElFormItem label="版本"><ElInput v-model="managedForm.version" /></ElFormItem><ElFormItem label="插件包下载地址"><ElInput v-model="managedForm.downloadUrl" placeholder="https://.../plugin.zip" /></ElFormItem><ElFormItem label="简介"><ElInput v-model="managedForm.description" type="textarea" /></ElFormItem></ElForm><template #footer><ElButton @click="managedDialog=false">取消</ElButton><ElButton type="primary" :loading="managedSaving" @click="saveManaged">保存并发布</ElButton></template></ElDialog>
  </div>
</template>
<script setup lang="ts">
  import { computed, onMounted, ref } from 'vue'
  import { useRouter } from 'vue-router'
  import { ElMessage } from 'element-plus'
  import ResourceHeader from '@/components/plus-resource/ResourceHeader.vue'
  import { fetchDownloadPlugin, fetchPluginList, fetchTogglePlugin, saveManagedPlugin, type PluginInfo, type PluginSource } from '@/api/system-manage'
  const router = useRouter(); const loading = ref(false); const search = ref(''); const category = ref('all'); const rows = ref<PluginInfo[]>([]); const sources = ref<PluginSource[]>([]); const togglingId = ref(''); const downloadingId = ref(''); const managedDialog = ref(false); const managedSaving = ref(false); const managedForm = ref({ pluginId: '', category: 'other', name: '', version: '1.0.0', downloadUrl: '', description: '' })
  const filteredRows = computed(() => category.value === 'all' ? rows.value : rows.value.filter((item) => item.category === category.value))
  const categoryText = (value: string) => ({ payment: '支付插件', realname: '实名认证', other: '其他插件' })[value] || value
  const colorFor = (value: string) => ({ payment: 'purple', realname: 'blue', other: 'orange' })[value] || 'green'
  const loadPlugins = async () => { loading.value = true; try { const data = await fetchPluginList({ q: search.value || undefined }); rows.value = (data.categories || []).flatMap((group) => group.plugins); sources.value = data.sources || [] } catch (error: any) { ElMessage.error(error?.message || '插件目录加载失败') } finally { loading.value = false } }
  const toggle = async (plugin: PluginInfo) => { togglingId.value = plugin.id; try { await fetchTogglePlugin(plugin.id, !plugin.enabled); ElMessage.success(plugin.enabled ? '插件已停用' : '插件已启用'); await loadPlugins() } catch (error: any) { ElMessage.error(error?.message || '插件状态更新失败') } finally { togglingId.value = '' } }
  const download = async (plugin: PluginInfo) => { if (!plugin.downloadUrl) return; downloadingId.value = plugin.id; try { await fetchDownloadPlugin(plugin.id); ElMessage.success('插件已下载'); await loadPlugins() } catch (error: any) { ElMessage.error(error?.message || '插件下载失败') } finally { downloadingId.value = '' } }
  const goSources = () => router.push('/plus-resources/sources')
  const openManaged = () => { managedForm.value = { pluginId: '', category: 'other', name: '', version: '1.0.0', downloadUrl: '', description: '' }; managedDialog.value = true }
  const saveManaged = async () => { if (!managedForm.value.pluginId || !managedForm.value.name) { ElMessage.warning('请填写插件标识和名称'); return }; managedSaving.value = true; try { await saveManagedPlugin({ ...managedForm.value, published: true }); ElMessage.success('托管插件已发布'); managedDialog.value = false; await loadPlugins() } catch (error: any) { ElMessage.error(error?.message || '保存托管插件失败') } finally { managedSaving.value = false } }
  onMounted(loadPlugins)
</script>
<style scoped>
  .resource-page{padding:24px;background:#f6f8fc;min-height:100%;color:#172033}.toolbar{display:flex;justify-content:space-between;gap:12px;margin:18px 0 10px}.search{width:300px}.filters{display:flex;gap:10px}.source-filter{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:0 0 14px;color:#8b94a5;font-size:12px}.table-card{border:0;border-radius:14px;min-height:220px}.name{display:flex;align-items:center;gap:11px}.name small{display:block;max-width:300px;margin-top:4px;overflow:hidden;color:#8b94a5;font-size:11px;text-overflow:ellipsis;white-space:nowrap}.icon{display:grid;place-items:center;width:38px;height:38px;border-radius:10px;font-size:19px}.purple{background:#f0ebff;color:#7354c8}.blue{background:#eaf4ff;color:#3c83d7}.orange{background:#fff1e5;color:#d97729}.green{background:#e7f8ef;color:#2d9d68}.status{font-size:12px;color:#5e697c}.status i{display:inline-block;width:6px;height:6px;border-radius:50%;background:#b4bdca;margin-right:6px}.status i.on{background:#45bc88}.empty{display:flex;align-items:center;flex-direction:column;gap:10px;padding:36px;color:#8b94a5;text-align:center}.empty>svg{font-size:34px;color:#7354c8}.empty strong{color:#172033}.empty span{font-size:12px}.notice{display:flex;gap:6px;margin-top:14px;color:#7c879a;font-size:12px;line-height:18px}.notice svg{flex:0 0 auto;margin-top:2px}@media(max-width:700px){.resource-page{padding:12px}.toolbar{align-items:stretch;flex-direction:column}.search{width:100%}.filters{justify-content:space-between}.name small{max-width:160px}.table-card{overflow-x:auto}.notice{align-items:flex-start}}
</style>
